import type { Metadata } from "next";
import { Header, Footer, ContactUs, InitGSAP } from "@/components/layout/";
import { HeaderProvider } from "@/components/providers/header-context";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Loader } from "@/components/layout/loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const myFont = localFont({
  variable: "--font-tt-common",
  src: "../assets/fonts/ttCommon.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${myFont.variable} `}
      >
        <Loader />
        <HeaderProvider>
          <Header />
          <InitGSAP>
            {children}
            <ContactUs />
            <Footer />
          </InitGSAP>
        </HeaderProvider>
      </body>
    </html>
  );
}
