import type { Metadata } from "next";
import * as Layout from "@/components/layout";
import { HeaderProvider } from "@/components/providers";
import { geistMono, geistSans, myFont } from "@/assets/fonts";
import "./globals.css";
import { getGlobal } from "@/cms/global";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [global] = await getGlobal();

  console.log(global);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${myFont.variable} `}
      >
        <Layout.Loader />
        <HeaderProvider>
          <Layout.Header header={global?.data?.header} />
          <Layout.InitGSAP>
            {children}
            <Layout.ContactUs />
            <Layout.Footer footer={global?.data?.footer} />
          </Layout.InitGSAP>
        </HeaderProvider>
      </body>
    </html>
  );
}
